function dat = InitializeResultsTable(nTrialsTotal)

varnames = {'subjno', 'age', 'gender', 'handness', 'eyedness', ...
    'isPractice', 'viewdist', 'eccentricity',...
    ...
    'location', 'isWord', 'stimID', 'isPreview', 'isArabic', ...
    ...
    'referenceOri', 'tiltAngAbs','tiltDir',...
    'TposX', 'TposY', 'textLengthXDeg', 'textLengthYDeg', 'transLengthXDeg', 'transLengthYDeg', ...
    ...
    'TrialNum', 'BlockNum', 'blktrl', ...
    'prevOnsetFrm', 'cueOnsetFrm', 'saccOnsetFrm', 'saccOffsetFrm', 'targetOffFrm', ...
    'phase', 'noiseOri', ...
    ...
    'TC_FIXATION', 'TC_PREVIEW', 'TC_CUE', 'TC_TRAN', 'TC_TARGET', 'TC_TARGETOFF', 'TC_RESPONSE_ONSET', 'TC_RESPONSE_TIME',...
    ...
    'sacAmplOk', 'sacDirOk', 'SacEndPointX', 'SacEndPointY', 'SacEnd', ...
    'RTsacPTB', 'RTsacEndPTBabs', ...
    'RT2afc', 'resp_2afc', 'acc', ... button -> response pad; key -> keyboard
    ...
    'PreviewOnsetTime', 'CueOnsetTime', 'TransientOnsetTime', ...
    'saccOnsetTime', 'saccOffsetTime', 'curr_targetDur', 'targetFix_Dur', ...
    'TargetOnsetVBL', 'TargetOnsetTime', 'TargetOffsetVBL', 'startrt_2afc', ...
    ...
    'fc_recal', 'fcp_continue_counter', 'fcp_recal'};

% 0 -> numeric, 1 -> cell
vartypes = [0, 0, 0, 0, 0,...
    0, 0, 0,...
    ...
    0, 0, 0, 0, 0, ... Preview, etc.
    ...
    0, 0, 0, ... Tilt
    0, 0, 0, 0, 0, 0, ... Tpos
    ...
    0, 0, 0, ... trial
    0, 0, 0, 0, 0,...
    1, 1, ...
    ...
    0 ,0 ,0, 0, 0, 0, 0, 0,... TC
    ....
    0, 0, 0, 0, 0, ... Sac...Ok
    0, 0, ... RTsac
    0, 0, 0, ... manual response
    ...
    0, 0, 0, ... VBL and Time
    0, 0, 0, 0, ...
    0, 0, 0, 0, ...
	...
    0, 0, 0
    ];

dat = dataset();

for i = 1:numel(varnames)
    
    if vartypes(i) % 0 -> numeric, 1 -> cell
        dat.(varnames{i}) = cell(nTrialsTotal,1);
    else
        dat.(varnames{i}) = nan(nTrialsTotal,1);
    end

end

end